freebsd_instance:
  image: freebsd-12-1-release-amd64
  
env:
  CIRRUS_CLONE_DEPTH: 1
  GITHUB_TOKEN: ENCRYPTED[a94677c15265bbc9174f2a1ddfc338258b291c2bb255aafc972fbec59c7fcf44423940726b43723c0212652524814358]
  
task:
  # This name gets reported as a build status in GitHub
  name: freebsd-12-1-release-amd64
  stateful: false
  setup_script:
    - pkg install -y curl wget zip cmake pkgconf kf5-kwindowsystem kf5-extra-cmake-modules devel/kf5-kcoreaddons x11-toolkits/kf5-kguiaddons kf5-kconfigwidgets plasma5-kdecoration qt5-core qt5-x11extras qt5-widgets qt5-qmake qt5-buildtools qt5-linguisttools
  test_script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DKDE_INSTALL_LIBDIR=lib -DBUILD_TESTING=OFF -DKDE_INSTALL_USE_QT_SYS_PATHS=ON
    - make -j$(sysctl -n hw.ncpu)
    # sudo make install
    - mkdir -p files
    - make DESTDIR=files install ; find files
    - wget "https://raw.githubusercontent.com/helloSystem/ISO/experimental/scripts/build-pkg.sh"
    - sh -ex ./build-pkg.sh -m  ../packaging/manifest -d ./files
    - case "$CIRRUS_BRANCH" in *pull/*) echo skipping since PR ;; * ) wget https://github.com/tcnksm/ghr/files/5247714/ghr.zip ; unzip ghr.zip ; rm ghr.zip ; ./ghr -replace -t "${GITHUB_TOKEN}" -u "${CIRRUS_REPO_OWNER}" -r "${CIRRUS_REPO_NAME}" -c "${CIRRUS_CHANGE_IN_REPO}" continuous "${CIRRUS_WORKING_DIR}"/build/*txz ; esac
  only_if: $CIRRUS_TAG != 'continuous'
